Cray-HPE/cray-nls-charts

charts/v1.0/cray-nls/Chart.yaml
charts/v1.0/cray-nls/templates/pdb.yaml
charts/v1.0/cray-nls/templates/secret.yaml
charts/v1.0/cray-nls/templates/service.yaml
charts/v1.0/cray-nls/templates/virtualservice.yaml
charts/v1.0/cray-nls/values.yaml

- deploy of argo-workflow as dependency
- deploy cray-nls
* Resolves CASMPET-5680
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) …

CASMPET-5680 argo deployment

---

charts/v1.0/cray-nls/Chart.yaml
charts/v1.0/cray-nls/values.yaml
ct.yaml

use our image build
* Resolves CASMPET-5680
- Were continuous integration tests …

fix argo image location/path

---

charts/v1.0/cray-nls/Chart.yaml
charts/v1.0/cray-nls/values.yaml

- use new cray-nls image 
- fix istio path rewrite
* Resolves CASMPET-5735
- Were …

use new cray-nls image and fix istio path rewrite

---

charts/v1.0/cray-nls/Chart.yaml
charts/v1.0/cray-nls/values.yaml

fix gateways config to specify namespace of gateways
* Resolves [CASMINST-4887](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4887)
_How were the changes tested and success verified? If schema changes were part of this change, …

fix gateways config to specify namespace of gateways

---

charts/v1.0/cray-nls/Chart.yaml
charts/v1.0/cray-nls/templates/rbac.yaml
charts/v1.0/cray-nls/values.yaml

- update image version
- add new cluster role bindings for argo flow
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your …

update image version; add new cluster role bindings for argo flow

---

charts/v1.0/cray-nls/Chart.yaml
charts/v1.0/cray-nls/values.yaml

- add missing anit affinity for argo server
-  using latest nls image
- fix logging
* Resolves [CASMPET-5775](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5775)
_How were the changes tested and success verified? If schema changes …

Casmpet 5775

---

charts/v1.0/cray-nls/Chart.yaml
charts/v1.0/cray-nls/templates/configmap.yaml
charts/v1.0/cray-nls/values.yaml

update deployment so nls read workflow files from configmap
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade …

CASMPET-5681

---

charts/v1.0/cray-nls/Chart.yaml
charts/v1.0/cray-nls/values.yaml

make sure s3 configuration is enabled
- Were the …

CASMINST-4978 make sure s3 configuration is enabled

---

charts/v1.0/cray-nls/Chart.yaml
charts/v1.0/cray-nls/values.yaml

update image version

---

charts/v1.0/cray-nls/Chart.yaml
charts/v1.0/cray-nls/values.yaml

Chart version change to include storage functionality.
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation …

CASMINST-5004 chart update

---

charts/v1.0/cray-nls/templates/virtualservice.yaml

add services/customer-admin-gateway
- Were the …

CASMPET-5831 add services/customer-admin-gateway" to argo GUI

---

charts/v1.0/cray-nls/Chart.yaml
charts/v1.0/cray-nls/values.yaml

set STORAGE_REBUILD_WORKFLOW_FILES in cray-nls-charts
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade …

CASMINST-5117 add STORAGE_REBUILD_WORKFLOW_FILES env variable

---

charts/v1.0/cray-nls/Chart.yaml
charts/v1.0/cray-nls/values.yaml

CASMINST-5140 update chart

---

charts/v1.0/cray-nls/Chart.yaml

- use latest cray-service chart to apply pg fix
* Resolves [CASMPET-5880](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5880)
- Were the install/upgrade-based validation …

CASMPET-5880 use latest cray-service chart to apply pg fix

---

charts/v1.0/cray-nls/Chart.yaml
charts/v1.0/cray-nls/values.yaml

CASMPET-5883 update chart image version

---

charts/v2.0/cray-nls/Chart.yaml
charts/v2.0/cray-nls/values.yaml

Using a newer version of cray-nls: 0.9.17.
* Resolves [CASM-3727]
* Merge after `https://github.com/Cray-HPE/cray-nls/pull/145 `
* Not sure how to test this.
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? No.
- Were continuous integration tests run? If not, why? No
- Was upgrade tested? If not, why? No
- Was downgrade tested? If not, why? No
- Were new tests (or test issues/Jiras) created for this change? No
Low

CASM-3727: Using a newer version of cray-nls: 0.9.17.

---

charts/v2.0/cray-nls/Chart.yaml
charts/v2.0/cray-nls/values.yaml

IUF operator should conditionally include operations based IUF product manifest contents
Yes
* Resolves [CASMINST-5746](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5746)
frigg

CASMINST-5746

---

charts/v2.0/cray-nls/Chart.yaml
charts/v2.0/cray-nls/values.yaml

Update version of cray-nls because of the following issues:
* [CASMINST-5938](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5938)
* [CASMINST-5851](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5851)
* [CASMPET-6312](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6312)
* Resolves: 
* [CASMINST-5938](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5938)
* [CASMINST-5851](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5851)
* [CASMPET-6312](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6312)
frigg, lemondrop
Ran IUF, did node rebuilds
No

CASMINST-5938

---

charts/v2.0/cray-nls/Chart.yaml
charts/v2.0/cray-nls/values.yaml

Update cray-nls version to resolve CRAYSAT-1678
* Resolves [CRAYSAT-1678](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1678)

CRAYSAT-1678: Update cray-nls container image version

---

charts/v2.0/cray-nls/Chart.yaml
charts/v2.0/cray-nls/values.yaml

CASMINST-5982 abort worker rebuild on the backend

---

charts/v2.0/cray-nls/Chart.yaml
charts/v2.0/cray-nls/values.yaml

CASMTRIAGE-5041 use proper hostname for s3 bucket

---

charts/v2.0/cray-nls/Chart.yaml
charts/v2.0/cray-nls/values.yaml

CASMINST-5880 update version

---

charts/v2.0/cray-nls/Chart.yaml
charts/v2.0/cray-nls/values.yaml

Update cray-nls image version and bump chart version
* Resolves [CRAYSAT-1700](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1700)

CRAYSAT-1700: Update cray-nls image version and bump chart version

---

.gitignore
charts/v3.0/cray-iuf/Chart.yaml
charts/v3.0/cray-iuf/values.yaml
charts/v3.0/cray-nls/Chart.yaml
charts/v3.0/cray-nls/templates/configmap.yaml
charts/v3.0/cray-nls/templates/metacontrollers.yaml
charts/v3.0/cray-nls/templates/pdb.yaml
charts/v3.0/cray-nls/templates/rbac.yaml
charts/v3.0/cray-nls/templates/secret.yaml
charts/v3.0/cray-nls/templates/service.yaml
charts/v3.0/cray-nls/templates/virtualservice.yaml
charts/v3.0/cray-nls/values.yaml
cray-nls.compatibility.yaml

Update cray-nls chart to use the new postgres operator.
* Resolves CASMPET-6403
* `dorian`
- Was upgrade tested? If not, why? Y
- Was downgrade tested? If not, why? Y
- Were new tests (or test issues/Jiras) created for this change?
Low

CASMPET-6403: upgrade to new postgres

---

charts/v3.0/cray-iuf/Chart.yaml
charts/v3.0/cray-nls/Chart.yaml
charts/v3.0/cray-nls/values.yaml
cray-nls.compatibility.yaml

Upgrade Argo server to v3.4.5 to pull upstream bug fixes.
* Resolves CASM-3813
* `dorian`
Deployed new cray-nls & cray-iuf charts using v3.4.5 argo images, and made sure that argo server, workflow controller and cray-nls pods are up and running as expected.
- …

CASM-3813: upgrade Argo server to v3.4.5

---

.gitignore
charts/v3.0/cray-iuf/Chart.yaml
charts/v3.0/cray-iuf/values.yaml
charts/v3.0/cray-nls/Chart.yaml
charts/v3.0/cray-nls/values.yaml
cray-nls.compatibility.yaml

Upgrade metacontroller to v4.10.3 for CVE remediation (only 1 low severity issue with the latest version.)
* Resolves [CASMPET-6235](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6235)
* Change will also be needed in `release/1.4`
* `mug`
* Virtual Shasta (dorian)
Upgraded iuf to use the latest …

CASMPET-6235: upgrade metacontroller to v4.10.3

---

.gitignore
charts/v2.0/cray-iuf/Chart.yaml
charts/v2.0/cray-iuf/values.yaml
charts/v2.0/cray-nls/Chart.yaml
cray-nls.compatibility.yaml

Use metacontroller v4.10.3 for CVE remediation (only 1 low severity vulnerability in this version). Bumped chart versions to 2.0.0 to be consistent with compatibility matrix documented in this repo.
* Resolves CASMPET-6235
* Change will also be needed in `main`
* `mug`
Upgraded iuf chart, and …

CASMPET-6235: use metacontroller v4.10.3 for CSM 1.4.1

---

charts/v3.0/cray-iuf/Chart.yaml
charts/v3.0/cray-nls/Chart.yaml
charts/v3.0/cray-nls/values.yaml
cray-nls.compatibility.yaml

Updated cray-nls image and cray-nls, cray-iuf version
cray-nls.compatibility.yaml log section will be updated once testing is done.
_How were the changes tested and success verified? If schema changes …

Bumped cray-nls and cray-iuf version

---

charts/v2.0/cray-iuf/Chart.yaml
charts/v2.0/cray-nls/Chart.yaml
charts/v2.0/cray-nls/values.yaml
charts/v3.0/cray-iuf/Chart.yaml
charts/v3.0/cray-nls/Chart.yaml
charts/v3.0/cray-nls/values.yaml
cray-nls.compatibility.yaml

upversion because of bad tag and CSM build
* Resolves [CASMTRIAGE-5568](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-5568)
* Surtur
- Ran IUF
No

CASMTRIAGE-5568

---

charts/v4.0/cray-nls/Chart.yaml
charts/v4.0/cray-nls/values.yaml
cray-nls.compatibility.yaml

update chart version

---

.github/workflows/chart_lint_test_scan.yaml
charts/v4.0/cray-iuf/Chart.yaml
charts/v4.0/cray-nls/Chart.yaml
charts/v4.0/cray-nls/values.yaml
cray-nls.compatibility.yaml

changing cray-nls version from 4.1.0 to 4.1.2 for IUF-1.6.1 changes.
* [CASMTRIAGE-7134](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-7134)

cray-nls version update

---

charts/v5.0/cray-iuf/Chart.yaml
charts/v5.0/cray-nls/Chart.yaml
charts/v5.0/cray-nls/values.yaml
cray-nls.compatibility.yaml

updating cray-nls to 5.0.0
* Resolves [CASMINST-7104](https://jira-pro.it.hpe.com:8443/browse/CASMINST-7104), [CASM-4572](https://jira-pro.it.hpe.com:8443/browse/CASM-4572)
* https://github.com/Cray-HPE/cray-nls/pull/227
* starlord
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) created for this change?

CASMINST-7104 : cray-nls version update

---

charts/v5.0/cray-iuf/Chart.yaml
charts/v5.0/cray-nls/Chart.yaml
charts/v5.0/cray-nls/values.yaml
cray-nls.compatibility.yaml

updating cray-nls to 5.0.1
* Resolves [CASMTRIAGE-8345](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-8345)
* wasp
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) created for this change?

CASMTRIAGE-8345 updating cray-nls version
