- charts/v1.0/cray-nls/Chart.yaml
Use the new base chart to pull in security fixes in the latest postgres-db-backup image. Bumped the chart patch version.
* Resolves [[CASMPET-5873](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5873)
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your …
> CASMPET-5873: use the new base chart for CVE fix

- charts/v1.0/cray-nls/Chart.yaml
- charts/v1.0/cray-nls/templates/configmap.yaml
- charts/v1.0/cray-nls/values.yaml
add separate mount in cray-nls for storage workflows
Tested on vShasta with --dry-run to check for correct configuration.
* Related moving storage workflow in docs: https://github.com/Cray-HPE/docs-csm/pull/2340
> CASMPET-5916 add separate mount in cray-nls for storage workflows

- charts/v1.0/cray-nls/Chart.yaml
BREAK/FIX: Cray-nls needs to pick up the cray base chart version 8.1.5 to fix postgres restore incompatibility issue in CSM 1.2.2
_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_bugfix
* Resolves [CASMPET-6086](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6086)
* Change will also be needed in NA
* Future work required by NA
* Documentation changes required in NA
* Merge with/before/after NA`
_How were the changes tested and success verified? If schema changes were part of this change, how …
> CASMPET-6086 CSM 1.2.2 : BREAK/FIX: Cray-nls rebuild to pick up cray-services:8.1.5

- charts/v2.0/cray-nls/Chart.yaml
- charts/v2.0/cray-nls/values.yaml
fix sat template name; update versions to align cray-nls and cray-nls-charts.
* Resolves [CASM-3858](https://jira-pro.its.hpecorp.net:8443/browse/CASM-3858)
frigg
No
> CASM-3858 fix sat template name; update versions

- charts/v2.0/cray-nls/Chart.yaml
- charts/v2.0/cray-nls/values.yaml
Bump cray-nls container image version to 0.9.19 to pull in `vcs.repo_name` support.
* Resolves [CASMINST-5876](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5876)
> CASMINST-5876: Bump cray-nls container version

- charts/v2.0/cray-nls/Chart.yaml
- charts/v2.0/cray-nls/values.yaml
Update the version of the cray-nls container image specified in the cray-nls chart to 0.10.0 and bump the chart version.
Update the version of the cray-nls container image specified in the cray-nls chart to 0.10.0 and bump the chart version.
* Resolves [CASMINST-5679](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5679)
See https://github.com/Cray-HPE/cray-nls/pull/158
Low risk.
See https://github.com/Cray-HPE/cray-nls/pull/158
> CASMINST-5679: Update version of cray-nls in chart

- charts/v2.0/cray-nls/Chart.yaml
- charts/v2.0/cray-nls/templates/metacontrollers.yaml
- charts/v2.0/cray-nls/values.yaml
Finally fixes [CASMINST-5851](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5851)
The previous fix didn't work on lemondrop.
I hot-patched a new fix on lemondrop and let it run for a few days. It seems the new fix that was hot-patched has not produced any duplicate workflows.
About the new fix: it tweaks the timeout value for metacontroller from 10s to 30s. This gives enough time for the first call to complete on large stages such as deliver-product.
* Resolves [CASMINST-5851](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5851)
lemondrop
Ran `IUF run` multiple times and didn't notice any duplicate workflows.
No
> CASMINST-5851

- charts/v2.0/cray-nls/Chart.yaml
- charts/v2.0/cray-nls/values.yaml
This PR contains fixes for the following two issues:
* [CASMPET-6323](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6323) IUF abort taking a long time / hanging when pressing Ctrl+C
* [CASMINST-5988](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5988) BREAK/FIX: management-node-rollout breaks with "default" product containing jinja templates
Yes
* Resolves:
* [CASMPET-6323](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6323)
* [CASMINST-5988](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5988)
* Change will also be needed in docs-csm, cray-nls, …
> CASMPET-6323 and CASMINST-5988

- charts/v2.0/cray-nls/Chart.yaml
- charts/v2.0/cray-nls/values.yaml
[CASMPET-6336](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6336) BREAK/FIX: IUF run does not skip previous sessions' operations even when force=false
* Resolves [CASMPET-6336](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6336)
* 
Tested on gamora
Tested by running a full stack integration with IUF.
No
> CASMPET-6336

- charts/v2.0/cray-nls/Chart.yaml
- charts/v2.0/cray-nls/values.yaml
- charts/v3.0/cray-iuf/Chart.yaml
- charts/v3.0/cray-nls/Chart.yaml
- charts/v3.0/cray-nls/values.yaml
- cray-nls.compatibility.yaml
Issue: Try to run management node rollout with Management_Master first, then Management_Worker next. The second run doesn't work, and it keeps trying to do Management_Master.
Root cause: Patch activity was not implemented as a true patching capability ... it was basically replacing input parameters whenever it received a patch request where the input parameters at least had the media directory set. In a particular case, the admin was not even specifying media directory on the command line, and hence because of the absence of media directory, the change from Management_Master to Management_Worker was not being persisted.
Fix: Use proper patching capability, where a struct with pointers is used to unmarshal the incoming json so that we can detect the difference between an empty value that …
> CASMTRIAGE-5124 patch activity doesn't truly work like patch activity

- charts/v3.0/cray-iuf/Chart.yaml
- charts/v3.0/cray-nls/Chart.yaml
- charts/v3.0/cray-nls/values.yaml
- cray-nls.compatibility.yaml
Have cray-nls chart use cray-nls version 0.10.11.
Tested a cray-nls-chart upgrade on Dorian.
> CASMINST-6208 bump cray-nls version to 0.10.11

- .gitignore
- README.md
- charts/v2.0/cray-iuf/Chart.yaml
- charts/v2.0/cray-nls/Chart.yaml
- charts/v2.0/cray-nls/values.yaml
- charts/v3.0/cray-iuf/Chart.yaml
- charts/v3.0/cray-nls/Chart.yaml
- charts/v3.0/cray-nls/values.yaml
- charts/v4.0/cray-iuf/Chart.yaml
- charts/v4.0/cray-iuf/values.yaml
- charts/v4.0/cray-nls/Chart.yaml
- charts/v4.0/cray-nls/templates/configmap.yaml
- charts/v4.0/cray-nls/templates/metacontrollers.yaml
- charts/v4.0/cray-nls/templates/pdb.yaml
- charts/v4.0/cray-nls/templates/rbac.yaml
- charts/v4.0/cray-nls/templates/secret.yaml
- charts/v4.0/cray-nls/templates/service.yaml
- charts/v4.0/cray-nls/templates/virtualservice.yaml
- charts/v4.0/cray-nls/values.yaml
- cray-nls.compatibility.yaml
Remove installation of dependencies using zypper entirely to rely upon the host for dependencies.
We are removing these because the dependencies in the host are more up-to-date, as opposed to the embedding them within this container which doesn't get updated often.
Yes
* Resolves [CASM-4352](https://jira-pro.it.hpe.com:8443/browse/CASM-4352)
* Merged code PR: https://github.com/Cray-HPE/iuf-containers/pull/18
Drax
Removed internally embedded dependencies from the image, volume mounted the host /usr/bin directory, appended the $PATH inside the container, and checked if the …
> CASM-4352 Remove installation of dependencies using zypper entirely to rely upon the host for dependencies

- charts/v3.0/cray-iuf/Chart.yaml
- charts/v3.0/cray-nls/Chart.yaml
- charts/v3.0/cray-nls/values.yaml
- charts/v4.0/cray-iuf/Chart.yaml
- charts/v4.0/cray-nls/Chart.yaml
- charts/v4.0/cray-nls/values.yaml
- cray-nls.compatibility.yaml
Bumping the versions to correlate to these PRs:
https://github.com/Cray-HPE/cray-nls/pull/181/files
Ticket:
https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8623
> CASMCMS-8623: Updating stable-1.5 and main versions of nls and iuf

- charts/v3.0/cray-iuf/Chart.yaml
- charts/v3.0/cray-nls/Chart.yaml
- charts/v3.0/cray-nls/values.yaml
- charts/v4.0/cray-iuf/Chart.yaml
- charts/v4.0/cray-nls/Chart.yaml
- charts/v4.0/cray-nls/values.yaml
- cray-nls.compatibility.yaml
Bump cray-nls version to 4.0.3 for CSM 1.6 and to 3.1.9 for CSM 1.5.
This changes the cray-nls backend to now look for specific workflows for NCN type (worker, storage, master node) instead of just looking for a workflow called `management-nodes-rollout`.
* Resolves CASMPET-6732
* Dorian
Tested upgrading to the new cray-nls helm chart and running a workflow which previously would've caused an error.
> CASMPET-6732 bump cray-nls version

- charts/v3.0/cray-iuf/Chart.yaml
- charts/v3.0/cray-nls/Chart.yaml
- charts/v3.0/cray-nls/values.yaml
- charts/v4.0/cray-iuf/Chart.yaml
- charts/v4.0/cray-nls/Chart.yaml
- charts/v4.0/cray-nls/values.yaml
- cray-nls.compatibility.yaml
These changes are for having a graceful error when no --limit-management-rollout parameter is supplied to IUF during management-nodes-rollout
* Resolves [CASMTRIAGE-5951](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-5951)
Tested upgrade on Dorain. (CSM 1.6 vShasta)
> CASMTRIAGE-5951 bump cray-nls chart versions to 3.1.10 and 4.0.4

- charts/v4.0/cray-iuf/Chart.yaml
- charts/v4.0/cray-nls/Chart.yaml
- charts/v4.0/cray-nls/values.yaml
- cray-nls.compatibility.yaml
Bump cray-nls chart version to 4.0.5.
* Resolves [CASM-4557](https://jira-pro.it.hpe.com:8443/browse/CASM-4557)
Deployed successfully on mug. 
Low risk
> CASM-4557 bumb cray-nls image version to 4.0.5

- charts/v3.0/cray-iuf/Chart.yaml
- charts/v3.0/cray-nls/Chart.yaml
- charts/v3.0/cray-nls/values.yaml
- charts/v4.0/cray-iuf/Chart.yaml
- charts/v4.0/cray-nls/Chart.yaml
- charts/v4.0/cray-nls/values.yaml
Currently, whenever we install products with IUF, irrespective of how many products we are installing, there is always a single Argo workflow for each stage per IUF run.
The problem with this approach is when the number of products being installed is arbitrarily large. In that case, the Argo workflow becomes huge at runtime, and cross the resource limits of the underlying etcd resource (1mb) that Argo uses to store the workflows.
This means that during the running of this large Argo workflow, an error is thrown by etcd, which Argo does not react well to -- it continues to think the workflow is in progress and gets hung.
The 1mb limit is a hard limit and there is no way to increase it either on a per-resource basis or on a global basis.
This means that we need to support breaking up the …
> CASMTRIAGE-6206

- .gitignore
- charts/v3.0/cray-iuf/Chart.yaml
- charts/v3.0/cray-nls/Chart.yaml
- charts/v4.0/cray-iuf/Chart.yaml
- charts/v4.0/cray-nls/Chart.yaml
- cray-nls.compatibility.yaml
Rebuild cray-nls charts to pick up a bug fix from cray-postgtesql-1.0.4 for CSM 1.5 and CSM 1.6.
* Resolves [CASMPET-6869](https://jira-pro.it.hpe.com:8443/browse/CASMPET-6869)
* `fanta`
Manually applied the replication bug fix and verified that the replication issue was resolved.
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) created for this change?
Low.
> CASMPET-6869: rebuild to pick up cray-postgtesql-1.0.4

- charts/v4.0/cray-iuf/Chart.yaml
- charts/v4.0/cray-nls/Chart.yaml
- charts/v4.0/cray-nls/values.yaml
- cray-nls.compatibility.yaml
cray-nls version update from 4.0.9 to 4.0.10
* https://jira-pro.it.hpe.com:8443/browse/CASM-4606
* https://github.com/Cray-HPE/cray-nls/pull/211
> CASM-4606: Execution of management-nodes-rollout on m002

- charts/v4.0/cray-iuf/Chart.yaml
- charts/v4.0/cray-nls/Chart.yaml
- charts/v4.0/cray-nls/values.yaml
- cray-nls.compatibility.yaml
cray-nls version update from 4.0.10 to 4.0.11
* [CASMTRIAGE-6862](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-6862)
* https://github.com/Cray-HPE/cray-nls/pull/212`
> CASMTRIAGE-6862:IUF workflows seem to hang around indefinitely

- .github/workflows/build_and_release_charts.yaml
- charts/v4.0/cray-iuf/Chart.yaml
- charts/v4.0/cray-nls/Chart.yaml
- cray-nls.compatibility.yaml
Cray-nls chart picked up the latest cray-service chart. This is neccessary because the previous version the cray-service chart used has a cert-manager API that is removed in CSM 1.6. 
I tested an install and an upgrade of the cray-nls chart on Beau.
Low risk. This is only going into CSM 1.6.
> CASMPET-7061 Update cray-service chart version use by cray-nls

- charts/v4.0/cray-iuf/Chart.yaml
- charts/v4.0/cray-nls/Chart.yaml
- charts/v4.0/cray-nls/values.yaml
- cray-nls.compatibility.yaml
The cray-nls and cray-iuf charts needed to updated to add the `node-role.kubernetes.io/control-plane` toleration and to change the affinity label from `node-role.kubernetes.io/master` to `node-role.kubernetes.io/control-plane`. This is necessary for k8s 1.24 in CSM 1.6.
* Relates to [CASMPET-7078](https://jira-pro.it.hpe.com:8443/browse/CASMPET-7078)
Deployed charts on Beau (CSM 1.6, K8s 1.22). Argo workflow ran successfully.
Low risk change.
> CASMPET-7078 update cray-nls-chart to use control-plane label instead of master for k8s 1.24

- charts/v4.0/cray-iuf/Chart.yaml
- charts/v4.0/cray-nls/Chart.yaml
- charts/v4.0/cray-nls/values.yaml
- cray-nls.compatibility.yaml
cray-nls version updated from 4.0.12 to 4.0.13. Updating the chart versions as well.
* [CASMINST-6832](https://jira-pro.it.hpe.com:8443/browse/CASMINST-6832)
* https://github.com/Cray-HPE/cray-nls/pull/215
* https://github.com/Cray-HPE/cray-nls/pull/214
> CASMINST-6832 : version changes

- charts/v4.0/cray-iuf/Chart.yaml
- charts/v4.0/cray-nls/Chart.yaml
- cray-nls.compatibility.yaml
The cray-service chart version that should be used with k8s 1.24 in CSM 1.6 is 11.0.0. This PR bump the cray-service chart version in cray-nls.
* Relates to [CASMPET-7219](https://jira-pro.it.hpe.com:8443/browse/CASMPET-7219)
> CASMPET-7219 bump cray-service chart version to 11.0.0

- charts/v4.0/cray-iuf/Chart.yaml
- charts/v4.0/cray-nls/Chart.yaml
- charts/v4.0/cray-nls/crds/cray-nls.hpe.com_hooks.yaml
- charts/v4.0/cray-nls/values.yaml
- cray-nls.compatibility.yaml
The cray-nls.hpe.com_hooks crd has been created by the cray-nls pods. This has caused a minor race condition that causes one pod to restart right after deployment. This creates an issue when upgrading cray-nls with IUF or when moving cray-nls pods from one node to another while IUF is running.
The PR correctly creates this CRD by the chart. This stops the race condition and causes no pods to need to restart and should resolve issues seen with the IUF CLI.
The related cray-nls PR is: https://github.com/Cray-HPE/cray-nls/pull/216
* Resolves [CASMTRIAGE-7425](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-7425)
* Relates to [CASMTRIAGE-7402](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-7402).
* Tested fresh installs and upgrades on Beau (Vshasta2)
Low risk change
> CASMTRIAGE-7425-csm-1.6.1 create cray-nls.hpe.com_hooks crd via cray-nls chart

- charts/v4.0/cray-iuf/Chart.yaml
- charts/v4.0/cray-nls/Chart.yaml
- charts/v4.0/cray-nls/templates/pdb.yaml
- cray-nls.compatibility.yaml
In preparation for the Kubernetes upgrade to v1.32 in CSM v1.7, apiVersion `policy/v1beta1` needs to change to `policy/v1` since `policy/v1beta1` does not exist in K8s v1.32.  apiVersion `policy/v1` does exist in K8s v1.24, so works in CSM v1.6.
* Resolves [CASMPET-7247](https://jira-pro.it.hpe.com:8443/browse/CASMPET-7247)
Updated chart on beau with no issues.
```
pit:~/studenym/cray-nls # helm list -n argo
NAME    	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART                                	APP VERSION
cray-iuf	argo     	1       	2025-01-13 14:35:49.713223358 +0000 UTC	deployed	cray-iuf-4.1.2                       	0.1.0
cray-nls	argo     	4       	2025-01-13 19:35:03.130615296 +0000 UTC	deployed	cray-nls-4.1.3-20250113162125+c90978f	0.1.0 …
```
> CASMPET-7247: Use policy/v1 instead of policy/v1beta1 in cray-nls chart

- charts/v5.0/cray-iuf/Chart.yaml
- charts/v5.0/cray-nls/Chart.yaml
- charts/v5.0/cray-nls/values.yaml
- cray-nls.compatibility.yaml
cray-nls version updated from 4.12 to 4.2.0. Updating the chart versions as well.
cray-nls image compatible with >1.7.0 docs-csm
> CASMINST-6734: SW_ADMIN_PASSWORD variable is not required to be set for tests anymore

- charts/v5.0/cray-iuf/Chart.yaml
- charts/v5.0/cray-nls/Chart.yaml
- cray-nls.compatibility.yaml
Pick up new postgresql version for CSM 1.7.
Now this uses cray-postgresql chart: 2.0.0 and cray-service chart: 12.0.0.
* Resolves [CASMPET-7522](https://jira-pro.it.hpe.com:8443/browse/CASMPET-7522)
* Beau
Tested chart upgrade and downgrade.
(The main postgres upgrade is done previously via the postgres operator. This is a minor change.)
> CASMPET-7522 update cray-services to version 12.0.0 and cray-postgresql to 2.0.0
